local _M = {
    [1] = "Pack",
    [2] = "Error",
    [3] = "Operation",
    [4] = "CreateRole",
    [5] = "EnterChapter",
    [31] = "OpenBox",
    [32] = "GainBox",
    [11] = "Delete",
    [101] = "Role",
    [1071] = "Prop",
    [107] = "Props",
    [1021] = "Chapter",
    [102] = "Chapters",
    [51] = "FinishDailyMission",
    [1051] = "DailyMission",
    [105] = "DailyMissionList",
    [1061] = "Box",
    [106] = "Boxes",
    [108] = "Rewards",
    [12] = "SigninRecord",
    [13] = "SigninGet",
    [22] = "ShopGet",
    [21] = "ShopRecord",
    [15] = "MapRecordSave",
}
return _M