local _M = {
    [1] = "Pack",
    [2] = "Error",
    [3] = "CreateRole",
    [4] = "UpgradeQuality",
    [5] = "UpgradeStar",
    [6] = "UpgradeLevel",
    [7] = "Decompose",
    [8] = "EnterChapter",
    [9] = "EnterSection",
    [10] = "FinishSection",
    [11] = "FinishMission",
    [12] = "Delete",
    [13] = "Role",
    [14] = "Prop",
    [15] = "Props",
    [16] = "Equipment",
    [17] = "Equipments",
    [18] = "Chapter",
    [19] = "Chapters",
    [20] = "Section",
    [21] = "Sections",
    [22] = "Mission",
    [23] = "Missions",
    [24] = "Box",
    [25] = "Boxes",
}
return _M