local _M = {
    Pack = 1,
    Error = 2,
    CreateRole = 3,
    UpgradeStar = 4,
    UpgradeLevel = 5,
    Decompose = 6,
    EnterChapter = 7,
    EnterSection = 8,
    FinishSection = 9,
    FinishMission = 10,
    Delete = 11,
    Role = 12,
    Prop = 13,
    Props = 14,
    Equipment = 15,
    Equipments = 16,
    Chapter = 17,
    Chapters = 18,
    Section = 19,
    SectionResult = 20,
    Sections = 21,
    Mission = 22,
    Missions = 23,
    Box = 24,
    Boxes = 25,
}
return _M