local _M = {
    Pack = 1,
    Error = 2,
    CreateRole = 3,
    UpgradeQuality = 4,
    UpgradeStar = 5,
    UpgradeLevel = 6,
    Decompose = 7,
    EnterChapter = 8,
    EnterSection = 9,
    Delete = 10,
    Role = 11,
    Prop = 12,
    Props = 13,
    Equipment = 14,
    Equipments = 15,
    Chapter = 16,
    Chapters = 17,
    Section = 18,
    Sections = 19,
    Mission = 20,
    Missions = 21,
    Box = 22,
    Boxes = 23,
}
return _M